Adapted needlist for base_url rel path
useblocks/sphinxcontrib-needs pull request #440
Opened 2021-12-06 17:33 UTC by haiyangToAI

Fix #407

2021-12-09 23:02 UTC, arwedus commented
first test on my projects looks promising 👍🏼

2021-12-16 06:56 UTC, danwos requested changes

2021-12-16 06:56 UTC, danwos commented on sphinxcontrib/needs/diagrams_common.py
> +                if curr_path_sep in fromdocname:
if -statement could be combined with above if statement

2021-12-16 06:56 UTC, danwos commented on sphinxcontrib/needs/directives/needlist.py
> +                    if curr_path_sep in fromdocname:
same, here, one if-statement?

2021-12-16 06:56 UTC, danwos commented on sphinxcontrib/needs/roles/need_incoming.py
> +                            if curr_path_sep in fromdocname:
again :)

2021-12-16 06:56 UTC, danwos commented on sphinxcontrib/needs/roles/need_outgoing.py
> +
okay, we have the same code on different location.
That's hard to maintain, if we detect an error in it.
Then we need to fix it at >4 locations.

Any chance to create a common function for this? maybe in ``util.py``

2021-12-20 14:41 UTC, danwos approved these changes
Looks all good.
Great work.

2021-12-20 14:41 UTC, merged